### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by soutaro**
I'm planning to make the project distributed under the terms of the MIT license. (There is no LICENSE file in this repo, so it is *undefined* now.)

Please tell me if you have any other opinion, contributors! @koic @pocke @wata727 @vzvu3k6k @yoshoku @shinnn @kohtaro24 @gfx

### CODE REVIEW

**Comment by soutaro** [comment]
I will merge this in 2 days.

**Comment by pocke** [comment]
I agree with MIT license.

BTW, gemspec also has license. e.g. https://github.com/cookpad/expeditor/blob/5e6e1b21418aac48be19577e6d147d8d7752ad5d/expeditor.gemspec#L11

**Comment by mre** [comment]
Any update on this?

**Comment by gfx** [comment]
Agreed 👏

**Pull request merged**
